### ISSUE TITLE
下载up失败

### ISSUE THREAD

**Issue by lengyijun** [sodaling/FastestBilibiliDownloader#36]
```
请输入想要下载的视频网址/up主个人主页网址: https://space.bilibili.com/626863/       
2023/01/21 22:38:48 开始下载...
panic: runtime error: integer divide by zero

goroutine 9 [running]:
simple-golang-crawler/parser.getNewBilibiliUpSpaceReqList({0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0xc00009a000?)
       FastestBilibiliDownloader/parser/aid.go:64 +0x689
simple-golang-crawler/parser.UpSpaceParseFun({0xc000228000?, 0x6a?, 0x0?}, {0xc000200050?, 0xc000200000?})
       FastestBilibiliDownloader/parser/aid.go:31 +0x1e5
simple-golang-crawler/engine.work(0xc00002e2e0)
       FastestBilibiliDownloader/engine/concurrent.go:109 +0xb1
simple-golang-crawler/engine.CreateWorker.func1()
       FastestBilibiliDownloader/engine/concurrent.go:93 +0x99
created by simple-golang-crawler/engine.CreateWorker
       FastestBilibiliDownloader/engine/concurrent.go:89 +0xaa
```

go version go1.19.5 linux/amd64

**Comment by lengyijun** [comment]
又可以了

**Comment by learner-dhx** [comment]
> 又可以了

@lengyijun 请问是怎么可以的，之前是什么问题？
