### ISSUE TITLE
单视频可以下 用户视频下载报错

### ISSUE THREAD

**Issue by moE-1111** [sodaling/FastestBilibiliDownloader#40]
请输入想要下载的视频网址/up主个人主页网址: https://space.bilibili.com/8203563/
2023/08/18 13:31:58 开始下载...
panic: runtime error: integer divide by zero
goroutine 8 [running]:
simple-golang-crawler/parser.getNewBilibiliUpSpaceReqList({0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0xc000358000?)
        C:/Users/Mo2022/Documents/golangProject/FastestBilibiliDownloader-master/parser/aid.go:64 +0x5ac
simple-golang-crawler/parser.UpSpaceParseFun({0xc0001e8000?, 0x6b?, 0x0?}, {0xc00007a2f8?, 0x100000000000000?})
        C:/Users/Mo2022/Documents/golangProject/FastestBilibiliDownloader-master/parser/aid.go:31 +0x1cf
simple-golang-crawler/engine.work(0xc0000686c0)
        C:/Users/Mo2022/Documents/golangProject/FastestBilibiliDownloader-master/engine/concurrent.go:109 +0x9e
simple-golang-crawler/engine.CreateWorker.func1()
        C:/Users/Mo2022/Documents/golangProject/FastestBilibiliDownloader-master/engine/concurrent.go:93 +0x79
created by simple-golang-crawler/engine.CreateWorker in goroutine 1
        C:/Users/Mo2022/Documents/golangProject/FastestBilibiliDownloader-master/engine/concurrent.go:89 +0x94

**Comment by boyuaner** [comment]
俺也一样

**Comment by chased9166** [comment]
_getAidUrlTemp 这个接口失效了，没有获取到数据，返回{"code":-799,"message":"请求过于频繁，请稍后再试","ttl":1}
导致后面func getNewBilibiliUpSpaceReqList函数中解析空数据出现了除0异常。

**Comment by boyuaner** [comment]
> _getAidUrlTemp 这个接口失效了，没有获取到数据，返回{"code":-799,"message":"请求过于频繁，请稍后再试","ttl":1} 导致后面func getNewBilibiliUpSpaceReqList函数中解析空数据出现了除0异常。

请问目前有解决方案吗？

**Comment by youzeliang** [comment]
确实，b站队接口进行了升级， 可以发现在作者代码仓库里aid.go的_getAidUrlTemp 变量里，接口不再是https://api.bilibili.com/x/space/arc/search?mid=%d&ps=30&tid=0&pn=%d&keyword=&order=pubdate&jsonp=jsonp，

然后访问一下b站up的分页视频，发现请求的接口已经是变成了  https://api.bilibili.com/x/space/wbi/arc/search?mid=171474500&ps=30&tid=0&pn=2&keyword=&order=pubdate&platform=web&web_location=1550101&order_avoided=true&dm_img_list=[%7B%22x%22:1781,%22y%22:596,%22z%22:0,%22timestamp%22:51367,%22type%22:0%7D,%7B%22x%22:1020,%22y%22:863,%22z%22:19,%22timestamp%22:51467,%22type%22:0%7D,%7B%22x%22:961,%22y%22:928,%22z%22:117,%22timestamp%22:51569,%22type%22:0%7D,%7B%22x%22:965,%22y%22:821,%22z%22:86,%22timestamp%22:51670,%22type%22:0%7D,%7B%22x%22:1046,%22y%22:824,%22z%22:125,%22timestamp%22:51771,%22type%22:0%7D,%7B%22x%22:1442,%22y%22:1206,%22z%22:517,%22timestamp%22:51871,%22type%22:0%7D,%7B%22x%22:1596,%22y%22:1329,%22z%22:649,%22timestamp%22:51971,%22type%22:0%7D,%7B%22x%22:976,%22y%22:690,%22z%22:17,%22timestamp%22:52071,%22type%22:0%7D,%7B%22x%22:1042,%22y%22:718,%22z%22:59,%22timestamp%22:52172,%22type%22:0%7D,%7B%22x%22:1534,%22y%22:1203,%22z%22:549,%22timestamp%22:52274,%22type%22:0%7D,%7B%22x%22:1103,%22y%22:772,%22z%22:118,%22timestamp%22:52526,%22type%22:0%7D,%7B%22x%22:1495,%22y%22:1152,%22z%22:500,%22timestamp%22:52630,%22type%22:0%7D,%7B%22x%22:2303,%22y%22:1953,%22z%22:1306,%22timestamp%22:52731,%22type%22:0%7D,%7B%22x%22:1647,%22y%22:1297,%22z%22:650,%22timestamp%22:52834,%22type%22:0%7D,%7B%22x%22:1608,%22y%22:1239,%22z%22:599,%22timestamp%22:52935,%22type%22:0%7D,%7B%22x%22:2397,%22y%22:2028,%22z%22:1388,%22timestamp%22:53450,%22type%22:0%7D,%7B%22x%22:2347,%22y%22:1776,%22z%22:1369,%22timestamp%22:53550,%22type%22:0%7D,%7B%22x%22:2373,%22y%22:1654,%22z%22:1471,%22timestamp%22:53655,%22type%22:0%7D,%7B%22x%22:1234,%22y%22:515,%22z%22:332,%22timestamp%22:53979,%22type%22:1%7D,%7B%22x%22:2303,%22y%22:1333,%22z%22:1487,%22timestamp%22:54080,%22type%22:0%7D,%7B%22x%22:1721,%22y%22:255,%22z%22:1082,%22timestamp%22:54181,%22type%22:0%7D,%7B%22x%22:927,%22y%22:-652,%22z%22:282,%22timestamp%22:54283,%22type%22:0%7D,%7B%22x%22:2069,%22y%22:536,%22z%22:1309,%22timestamp%22:56923,%22type%22:0%7D,%7B%22x%22:2383,%22y%22:1418,%22z%22:1598,%22timestamp%22:57023,%22type%22:0%7D,%7B%22x%22:3293,%22y%22:2336,%22z%22:2507,%22timestamp%22:57125,%22type%22:0%7D,%7B%22x%22:2634,%22y%22:1677,%22z%22:1848,%22timestamp%22:57303,%22type%22:1%7D,%7B%22x%22:1840,%22y%22:885,%22z%22:1048,%22timestamp%22:57403,%22type%22:0%7D,%7B%22x%22:2534,%22y%22:2003,%22z%22:148,%22timestamp%22:57504,%22type%22:0%7D,%7B%22x%22:5276,%22y%22:4985,%22z%22:1526,%22timestamp%22:57605,%22type%22:0%7D,%7B%22x%22:7076,%22y%22:6785,%22z%22:3303,%22timestamp%22:57706,%22type%22:0%7D,%7B%22x%22:4093,%22y%22:3804,%22z%22:314,%22timestamp%22:57807,%22type%22:0%7D,%7B%22x%22:5058,%22y%22:4804,%22z%22:1358,%22timestamp%22:57908,%22type%22:0%7D,%7B%22x%22:6428,%22y%22:6167,%22z%22:2772,%22timestamp%22:58009,%22type%22:0%7D,%7B%22x%22:4595,%22y%22:4340,%22z%22:967,%22timestamp%22:58111,%22type%22:0%7D]&dm_img_str=V2ViR0wgMS4wIChPcGVuR0wgRVMgMi4wIENocm9taXVtKQ&dm_cover_img_str=QU5HTEUgKEFwcGxlLCBBTkdMRSBNZXRhbCBSZW5kZXJlcjogQXBwbGUgTTIsIFVuc3BlY2lmaWVkIFZlcnNpb24pR29vZ2xlIEluYy4gKEFwcGxlKQ&w_rid=c36c977b4ad439ed001ed3be32319cd2&wts=1704562796

类似于这样的，仔细观察，dm_img_list 里的是 %7B%22x%22:1781  比如这样的，代表的是 {  "x": 1781}  在URL编码中，"%7B"代表左花括号 "{"，而"%7D"代表右花括号 "}"。URL编码是一种将特殊字符转换为URL安全格式的方法，通常在将数据包含在URL中时使用。 所以 他的x，y，z 还有其他的一些参数之间就肯定会存在一种联系，你修改了一些参数的话，b站的网关就估计给你权限拦截了。
